spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/implantation_db
    username: implantation_user
    password: implantation_pass

  jpa:
    show-sql: true
